; PlatformIO — daha hızlı flash için
; brew install platformio
; pio run -t upload
[env:m5stack-core2]
platform = espressif32
board = m5stack-core2
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
build_src_filter = +<*> +<../Core2Buddy.ino>
lib_deps =
    m5stack/M5Unified@^0.1.17
    bblanchon/ArduinoJson@^7.0.4
